#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#==============================================================================
#
# This file is a part of mygtd.
#
# File: start_today.py
# Description: .
# Author: Yu Zhao 赵宇 <zyzy5730@163.com>
# Created: 2012-10-05 10:31:52
# Last modified: 2012-10-06 00:22:40
#
# Copyright (C) 2012-2013 Yu Zhao.
#
#==============================================================================

import wx
import logging
logger = logging.getLogger('add_gtd')

import controller as ct

# TODO: no! use a dialog
class StartTodayPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        topSizer = wx.BoxSizer(wx.HORIZONTAL)
        # Add a Choice for Catagories, a ComboBox for Tasks,
        # a Choice for big_or_not, and a "Add" Button
        # EVT_COMBOBOX(id, func) 	Process a wxEVT_COMMAND_COMBOBOX_SELECTED command, which is generated by a wxComboBox control. 
        cat_choice = wx.ComboBox(self, -1, choices=ct.getCatagoryNameList()) 
        topSizer.Add(cat_choice)
        taskBox = wx.ComboBox(self, -1, choices=[])
        topSizer.Add(taskBox)
        big_choice = wx.Choice(self, -1, pos=wx.DefaultPosition,
                            size=wx.DefaultSize, choices=[u'1小时',u'2小时'], style=0,
                            validator=wx.DefaultValidator, name="choice") 
        topSizer.Add(big_choice)
        addBtn = wx.Button(self, label=u'Add', style=wx.BU_EXACTFIT)
        topSizer.Add(addBtn, flag=wx.RIGHT)
        addBtn.Bind(wx.EVT_BUTTON, self.onAdd)
        # TODO: add a ListView for showing today's schedule
        lvSizer = wx.BoxSizer(wx.HORIZONTAL)
        listview = wx.ListView(self)
        lvSizer.Add(listview, wx.EXPAND)
        botSizer = wx.BoxSizer(wx.VERTICAL)
        saveBtn = wx.Button(self, label='Save&&Start!', style=wx.BU_EXACTFIT)
        saveBtn.Bind(wx.EVT_BUTTON, self.onSave)
        botSizer.Add(saveBtn, flag=wx.ALIGN_CENTER)
        # TODO: 应该在listview中确认今日schedule，确认完毕后添加到数据库
        mainSizer.Add(topSizer, flag=wx.EXPAND)
        mainSizer.Add(lvSizer, flag=wx.EXPAND)
        mainSizer.Add(botSizer, flag=wx.EXPAND)
        self.SetSizer(mainSizer)
        self.SetAutoLayout(True)
    def onAdd(self, event):
        pass
    def onSave(self, event):
        pass

class StartTodayFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, None, -1, u"制定新一天的计划")
        panel = StartTodayPanel(self)
        #self.Show()
